# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='endereço de email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fullName',
            field=models.CharField(help_text='Entre com seu nome.', max_length=255, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='API_REST.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone1',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='telefone 1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone2',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='telefone 2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='matricula'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rg',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='rg'),
        ),
    ]
