# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='API_REST.Course'),
        ),
    ]
