# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0002_auto_20170916_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='número')),
                ('vacancy', models.IntegerField(verbose_name='vagas')),
                ('capacity', models.IntegerField(verbose_name='capacidade')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='id_apto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apto', to='API_REST.Apartament'),
        ),
    ]
