# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0002_auto_20170914_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.IntegerField(max_length=9, unique=True, verbose_name='matricula'),
        ),
    ]
