# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0003_auto_20170914_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.CharField(max_length=9, unique=True, verbose_name='matricula'),
        ),
    ]
