# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0003_auto_20170917_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='número')),
                ('buildNumber', models.IntegerField(unique=True, verbose_name='número do prédio')),
            ],
        ),
        migrations.AddField(
            model_name='apartament',
            name='id_apto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block', to='API_REST.Block'),
        ),
    ]
