# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_REST', '0004_auto_20170917_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartament',
            old_name='id_apto',
            new_name='id_block',
        ),
        migrations.AlterField(
            model_name='block',
            name='buildNumber',
            field=models.IntegerField(unique=True, verbose_name='número do prédio ao qual o bloco pertence'),
        ),
        migrations.AlterField(
            model_name='block',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='número do bloco'),
        ),
    ]
